[package]
name = "res_json"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
sapper = { git="https://github.com/sappworks/sapper.git" }
sapper_std = { git="https://github.com/sappworks/sapper_std.git" }
log = "*"
env_logger = "*"

serde="*"
serde_json="*"
