[package]
name = "mvc_example"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
sapper = { git="https://github.com/sappworks/sapper.git" }
sporm = { git="https://github.com/sappworks/sporm.git" }
log = "0.3"
env_logger = "0.3"
dotenv = "0.8"
typemap = "0.3"
